---
title: "R Notebook"
output:
  word_document: default
  html_notebook: default
  pdf_document: default
  html_document:
    df_print: paged
---
```{r, load library, include=FALSE}
# load the library tidyverse, which contains dplyr as well as 
# several other useful tools
library(tidyverse)
```

Comments can be added outside or inside each chunk. If inside a chunk, 
remember to use # before each line.
```{r}
# starwars dataset is part of the tidyverse library
summarise(starwars, average_height = mean(height, na.rm=TRUE))
summarise(starwars, average_mass = mean(mass, na.rm=TRUE))
```

```{r}
# use dplyr (pipe) for a more succinct output
starwars %>% summarise(average_height = mean(height, na.rm=TRUE), 
                       average_mass = mean(mass, na.rm=TRUE))
```

```{r}
# group_by
mean_height_mass_by_species <- starwars %>% group_by(species) %>% 
  summarise(average_height = mean(height, na.rm=TRUE), average_mass = mean(mass, na.rm=TRUE))

```

```{r}
# select
tempdata <- starwars %>% select(name, height, mass, gender, species)
```

```{r}
# mutate
bmi_data <- tempdata %>% 
  mutate(height = height/100) %>% 
  mutate(BMI = mass / height^2)

```

```{r}
# filter
bmi_data_human <- bmi_data %>% 
  filter(species == "Human") %>% 
  na.omit
```


```{r}
# arrange
bmi_data_human <- bmi_data %>% 
  filter(species == "Human") %>% 
  na.omit %>% 
  arrange(desc(BMI))

```

```{r}
# summarise
bmi_data_human %>% 
  group_by(gender) %>% 
  summarise(Average_BMI = mean(BMI, na.rm=TRUE))
  
```

